export enum TransactionType {
    TOP_UP = "top_up",
    WITHDRAW = "withdraw",
}

export enum TransactionSource {
    ARMONEY = "armoney",
    CUSTOM = "custom",
    CRYPTOMUS = "cryptomus",
}

export enum TransactionStatus {
    CREATE = "CREATE",

    QUEUE_FOR_WITHDRAW = "QUEUE_FOR_WITHDRAW",
    PROGRESS_TO_WITHDRAW = "PROGRESS_TO_WITHDRAW",
    WITHDRAW = "WITHDRAW",

    WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT",
    WAITING_FOR_PAYMENT_CONFIRMATION = "WAITING_FOR_PAYMENT_CONFIRMATION",
    PAID = "PAID",
    PAID_OVER = "PAID_OVER",
    WRONG_AMOUNT = "WRONG_AMOUNT",
    TIMEOUT = "TIMEOUT",

    CANCELLED = "CANCELLED",
    USER_CANCELLED = "USER_CANCELLED",

    INCORRECT_AMOUNT = "INCORRECT_AMOUNT",
    RESTORED = "RESTORED",
}

export enum TransactionCurrency {
    RUB = "rub",
    USD = "usd",
    USDT = "usdt",
}

export enum TransactionAppealState {
    NOT_SET = "NOT_SET",
    APPEALED = "APPEALED",
    USER_SUCCESS = "USER_SUCCESS",
    TRADER_SUCCESS = "TRADER_SUCCESS",
}

export enum TransactionAppealReason {
    TRADER_NOT_CONFIRM_PAYMENT = "TRADER_NOT_CONFIRM_PAYMENT",
    OVERPAYMENT = "OVERPAYMENT",
    INVOICE_EXPIRED_WITH_PAYMENT = "INVOICE_EXPIRED_WITH_PAYMENT",
    FRAUD = "FRAUD",
    PAYMENT_NOT_RECEIVED = "PAYMENT_NOT_RECEIVED",
    BUYER_PAID_LESS = "BUYER_PAID_LESS",
    MALICIOUS_ORDER_CANCELLATION = "MALICIOUS_ORDER_CANCELLATION",
    CONFIRMATION_DOCUMENTS = "CONFIRMATION_DOCUMENTS",
    BANK_ACCOUNT_FROZEN = "BANK_ACCOUNT_FROZEN",
    NEW_AMOUNT = "NEW_AMOUNT",
    OTHER = "OTHER",
}
